data:
  train_dataset: all
  val_dataset: igr/202305031337_hBreast-slide-B-4h-photobleach_VMSC09302

model_kwargs:
  batch_size: 256
  scgpt_model_dir: /mnt/beegfs/userdata/q_blampey/data/checkpoints/scgpt/scGPT_human

trainer_kwargs:
  max_epochs: 50
  accelerator: "gpu"
  num_workers: 16
  patience: 10
