project: novae_infer
wandb_artefact: novae/novae/model-73gex5vi:v4
train_inference: true

data:
  train_dataset: all
  val_dataset: infer/lung_merscope_infer.h5ad
  files_black_list: ["HumanLungCancerPatient1_region_0.h5ad"]

fit_kwargs:
  max_epochs: 30
  lr: 0.0001
  accelerator: "gpu"
  num_workers: 8
  patience: 2
  min_delta: 4
