data:
  train_dataset: all
  val_dataset: igr/202305031337_hBreast-slide-B-4h-photobleach_VMSC09302

model_kwargs:
  scgpt_model_dir: /gpfs/workdir/blampeyq/checkpoints/scgpt/scGPT_human
  n_hops_view: 3
  heads: 16
  hidden_size: 128
  temperature: 0.1
  temperature_weight_proto: 0.05
  num_prototypes: 512
  background_noise_lambda: 5
  panel_subset_size: 0.8
  lambda_regularization: 0

fit_kwargs:
  max_epochs: 50
  lr: 0.0001
  accelerator: "gpu"
  num_workers: 8
  patience: 6
  min_delta: 0.025

save_umap: 20
