data:
  train_dataset: all
  val_dataset: igr/202305031337_hBreast-slide-B-4h-photobleach_VMSC09302

model_kwargs:
  n_hops_view: 2
  heads: 8
  hidden_size: 128
  scgpt_model_dir: /mnt/beegfs/userdata/q_blampey/data/checkpoints/scgpt/scGPT_human
  temperature: 0.1
  background_noise_lambda: 5

trainer_kwargs:
  max_epochs: 50
  accelerator: "gpu"
  num_workers: 8
  patience: 10
