data:
  train_dataset: dummy2
  val_dataset: false

model_kwargs:
  n_hops: 2
  n_intermediate: 4
  heads: 4
  embedding_size: 30

trainer_kwargs:
  max_epochs: 1
  log_every_n_steps: 10
  accelerator: "cpu"

wandb_init_kwargs:
  mode: "online"
