data:
  train_dataset: igr/202309261341_breast-santiago-slide2_VMSC09302
  val_dataset: igr/202309261341_breast-santiago-slide2_VMSC09302

model_kwargs:
  n_hops_local: 2
  n_hops_view: 3
  hidden_size: 256

trainer_kwargs:
  max_epochs: 2
  accelerator: "gpu"
  profiler: "simple"
  num_workers: 8
