data:
  train_dataset: dummy_train
  val_dataset: igr/202305031337_hBreast-slide-B-4h-photobleach_VMSC09302

model_kwargs:
  embedding_size: 50
  scgpt_model_dir: /gpfs/workdir/blampeyq/checkpoints/scgpt/scGPT_human

fit_kwargs:
  max_epochs: 5
  accelerator: "gpu"
  num_workers: 8

project: novae_tests
