data:
  train_dataset: sdm_bench
  val_dataset: sdm_bench

model_kwargs:
  n_hops_local: 2
  n_hops_view: 3
  heads: 4

trainer_kwargs:
  max_epochs: 1
  log_every_n_steps: 10
  accelerator: "cpu"

wandb_init_kwargs:
  mode: "disabled"
