data:
  train_dataset: sdm_bench
  val_dataset: sdm_bench

model_kwargs:
  n_hops_local: 2
  n_hops_ngh: 3
  heads: 4

trainer_kwargs:
  max_epochs: 1
  accelerator: "gpu"

wandb_init_kwargs:
  mode: "disabled"
