data:
  train_dataset: dummy_train
  val_dataset: dummy_val

model_kwargs:
  embedding_size: 50

fit_kwargs:
  max_epochs: 1
  accelerator: "cpu"

project: novae_tests

post_training:
  save_umap: 7
  save_metrics: true
