data:
  train_dataset: igr/santiago_tumour_total_annot_epoch75_integrated_Niche_Domain_Pathway.h5ad

model_kwargs:
  scgpt_model_dir: /mnt/beegfs/userdata/q_blampey/data/checkpoints/scgpt/scGPT_human

trainer_kwargs:
  max_epochs: 10
  accelerator: "gpu"
  num_workers: 8

save_result: "santiago_novae"
