data:
  train_dataset: example.h5ad
  val_dataset: example.h5ad

model_kwargs:
  swav: false
  n_hops_local: 2
  n_hops_ngh: 3
  heads: 4

trainer_kwargs:
  max_epochs: 1
  log_every_n_steps: 10
  accelerator: "cpu"
  #fast_dev_run: True
