data:
  train_dataset: igr/202309261341_breast-santiago-slide2_VMSC09302
  val_dataset: false

model_kwargs:
  n_hops_local: 2
  n_hops_ngh: 3
  epoch_unfreeze_prototypes: 1
  heads: 4

trainer_kwargs:
  max_epochs: 30
