data:
  train_dataset: igr/202309261341_breast-santiago-slide2_VMSC09302
  val_dataset: igr/202305031337_hBreast-slide-B-4h-photobleach_VMSC09302

model_kwargs:
  n_hops_local: 2
  n_hops_view: 3
  heads: 4

trainer_kwargs:
  max_epochs: 30
