data:
  train_dataset: igr/202309261341_breast-santiago-slide2_VMSC09302
  eval_dataset: false

model_kwargs:
  n_hops: 2
  n_intermediate: 4
  heads: 4

trainer_kwargs:
  max_epochs: 30
  accelerator: "gpu"
