site_name: novae
repo_name: novae
copyright: Copyright &copy; 2024 Quentin Blampey
theme:
  name: material
nav:
  - Home: index.md
  - API:
    - novae.Novae: api/novae.Novae.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 2
            extensions:
            - docs/format_docstrings.py
  - mkdocs-jupyter:
      include_source: True
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
