site_name: Novae
repo_name: MICS-Lab/novae
repo_url: https://github.com/MICS-Lab/novae
copyright: Copyright &copy; 2024 Quentin Blampey
theme:
  name: material
  logo: assets/logo_small_black.png
  favicon: assets/logo_favicon.png
  palette:
    scheme: slate
    primary: white
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Tutorials:
    - Main usage: tutorials/main_usage.ipynb
    - Different input modes: tutorials/input_modes.md
    - Usage on proteins: tutorials/proteins.ipynb
    - Spot/bin/single-cell resolutions: tutorials/resolutions.ipynb
    - Multi tissue/condition mode: tutorials/multi_tissue.ipynb
  - API:
    - Novae model: api/Novae.md
    - Utils: api/utils.md
    - Plotting: api/plot.md
    - Advanced:
      - Metrics: api/metrics.md
      - Modules: api/modules.md
      - Dataloader: api/dataloader.md
  - FAQ: faq.md
  - Cite us: cite_us.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 3
  - mkdocs-jupyter:
      include_source: True
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
