site_name: Novae
repo_name: MICS-Lab/novae
repo_url: https://github.com/MICS-Lab/novae
copyright: Copyright &copy; 2024 Quentin Blampey
theme:
  name: material
  logo: assets/logo_small_black.png
  favicon: assets/logo_favicon.png
  palette:
    scheme: slate
    primary: white
nav:
  - Home: index.md
  - API:
    - novae.Novae: api/novae.Novae.md
    - novae.utils: api/novae.utils.md
    - novae.plot: api/novae.plot.md
    - novae.monitor: api/novae.monitor.md
    - novae.module:
      - novae.module.GraphAugmentation: api/novae.module.GraphAugmentation.md
      - novae.module.CellEmbedder: api/novae.module.CellEmbedder.md
      - novae.module.GraphEncoder: api/novae.module.GraphEncoder.md
      - novae.module.AttentionAggregation: api/novae.module.AttentionAggregation.md
      - novae.module.SwavHead: api/novae.module.SwavHead.md
      - novae.module.InferenceHeadZIE: api/novae.module.InferenceHeadZIE.md
    - novae.data:
      - novae.data.NovaeDataset: api/novae.data.NovaeDataset.md
      - novae.data.NovaeDatamodule: api/novae.data.NovaeDatamodule.md
      - novae.data.AnnDataTorch: api/novae.data.AnnDataTorch.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 2
            extensions:
            - docs/format_docstrings.py
  - mkdocs-jupyter:
      include_source: True
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
