mode: shuffle
use_wandb: false

data:
  train_dataset: example.h5ad
  eval_dataset: example.h5ad

model_kwargs:
  n_hops: 2
  n_intermediate: 4
  heads: 4

trainer_kwargs:
  max_epochs: 1
  log_every_n_steps: 10
  accelerator: "mps"
  #fast_dev_run: True