mode: swav
use_wandb: true

data:
  train_dataset: sdm_bench
  eval_dataset: sdm_bench

model_kwargs:
  n_hops: 2
  n_intermediate: 4
  heads: 4

trainer_kwargs:
  max_epochs: 5
  log_every_n_steps: 10
  accelerator: "cpu"
  #fast_dev_run: True