data:
  train_dataset: sdm_bench
  eval_dataset: sdm_bench

model_kwargs:
  heads: 4

trainer_kwargs:
  max_epochs: 1
  log_every_n_steps: 10
  accelerator: "cpu"

sweep:
  count: 2
  configuration:
    method: random
    metric:
      goal: minimize
      name: train/loss_epoch
    parameters:
      heads:
        values: [1, 4, 8]
      lr:
        min: 0.0001
        max: 0.01

wandb_init_kwargs:
  mode: "online"
