data:
  train_dataset: all
  val_dataset: igr/202305031337_hBreast-slide-B-4h-photobleach_VMSC09302

model_kwargs:
  scgpt_model_dir: /gpfs/workdir/blampeyq/checkpoints/scgpt/scGPT_human
  n_hops_view: 3
  heads: 16
  num_prototypes: 512
  panel_subset_size: 0.8
  temperature: 0.1

fit_kwargs:
  max_epochs: 50
  accelerator: "gpu"
  num_workers: 8
  patience: 3
  min_delta: 0.05
