project: novae_eval

model_kwargs:
  scgpt_model_dir: /gpfs/workdir/blampeyq/checkpoints/scgpt/scGPT_human
  n_hops_view: 3
  heads: 16
  hidden_size: 128
  temperature: 0.1
  num_prototypes: 512
  background_noise_lambda: 5
  panel_subset_size: 0.8

data:
  train_dataset: colon

fit_kwargs:
  max_epochs: 20
  accelerator: "gpu"
  num_workers: 8
  patience: 3
  min_delta: 0.05

post_training:
  n_domains: [7, 10, 15]
  log_metrics: true
  save_h5ad: true
  log_umap: true
  log_domains: true
  delete_X: true
