project: novae_tests

data:
  train_dataset: toy_train

model_kwargs:
  n_hops_view: 2
  background_noise_lambda: 5
  panel_subset_size: 0.8
  min_prototypes_ratio: 0.6

fit_kwargs:
  max_epochs: 1
  accelerator: "cpu"
  patience: 4
  min_delta: 0.025

post_training:
  n_domains: [8, 10, 12]
  log_metrics: true
  log_domains: true
